---
- hosts: all
  become: true
  tasks:
  - name: Setup ssh keys
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', './root/.ssh/id_ed25519.pub') }}"
    with_items:
      - root
      - vagrant

